// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqSignup struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignup) Reset()         { *m = ReqSignup{} }
func (m *ReqSignup) String() string { return proto.CompactTextString(m) }
func (*ReqSignup) ProtoMessage()    {}
func (*ReqSignup) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ReqSignup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignup.Unmarshal(m, b)
}
func (m *ReqSignup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignup.Marshal(b, m, deterministic)
}
func (m *ReqSignup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignup.Merge(m, src)
}
func (m *ReqSignup) XXX_Size() int {
	return xxx_messageInfo_ReqSignup.Size(m)
}
func (m *ReqSignup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignup proto.InternalMessageInfo

func (m *ReqSignup) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqSignup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RespSignup struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSignup) Reset()         { *m = RespSignup{} }
func (m *RespSignup) String() string { return proto.CompactTextString(m) }
func (*RespSignup) ProtoMessage()    {}
func (*RespSignup) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RespSignup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignup.Unmarshal(m, b)
}
func (m *RespSignup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignup.Marshal(b, m, deterministic)
}
func (m *RespSignup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignup.Merge(m, src)
}
func (m *RespSignup) XXX_Size() int {
	return xxx_messageInfo_RespSignup.Size(m)
}
func (m *RespSignup) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignup.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignup proto.InternalMessageInfo

func (m *RespSignup) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespSignup) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReqLogin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RespLogin struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespLogin) Reset()         { *m = RespLogin{} }
func (m *RespLogin) String() string { return proto.CompactTextString(m) }
func (*RespLogin) ProtoMessage()    {}
func (*RespLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RespLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespLogin.Unmarshal(m, b)
}
func (m *RespLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespLogin.Marshal(b, m, deterministic)
}
func (m *RespLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespLogin.Merge(m, src)
}
func (m *RespLogin) XXX_Size() int {
	return xxx_messageInfo_RespLogin.Size(m)
}
func (m *RespLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RespLogin proto.InternalMessageInfo

func (m *RespLogin) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RespLogin) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSignup)(nil), "micro.service.user.ReqSignup")
	proto.RegisterType((*RespSignup)(nil), "micro.service.user.RespSignup")
	proto.RegisterType((*ReqLogin)(nil), "micro.service.user.ReqLogin")
	proto.RegisterType((*RespLogin)(nil), "micro.service.user.RespLogin")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xb7, 0x6a, 0xd7, 0xdd, 0xf1, 0x16, 0x3c, 0x94, 0xe2, 0x8a, 0xe4, 0xe4, 0x29, 0x07,
	0xbd, 0x79, 0x54, 0x10, 0x04, 0x41, 0xc8, 0xe2, 0x07, 0xa8, 0xdd, 0xa1, 0x04, 0x69, 0x92, 0x66,
	0x5a, 0xfd, 0x3a, 0x7e, 0x54, 0xc9, 0x9f, 0x16, 0xc5, 0xf6, 0xe2, 0xad, 0xaf, 0x3f, 0xe6, 0xcd,
	0x9b, 0x17, 0x80, 0x81, 0xd0, 0x09, 0xeb, 0x4c, 0x6f, 0x18, 0x6b, 0x55, 0xed, 0x8c, 0x20, 0x74,
	0x1f, 0xaa, 0x46, 0xe1, 0x09, 0x7f, 0x80, 0xad, 0xc4, 0x6e, 0xaf, 0x1a, 0x3d, 0x58, 0x56, 0xc2,
	0xc6, 0xff, 0xd4, 0x55, 0x8b, 0x45, 0x76, 0x95, 0x5d, 0x6f, 0xe5, 0xa4, 0x3d, 0xb3, 0x15, 0xd1,
	0xa7, 0x71, 0x87, 0xe2, 0x28, 0xb2, 0x51, 0xf3, 0x3b, 0x00, 0x89, 0x64, 0x93, 0x0b, 0x83, 0x93,
	0xda, 0x1c, 0xa2, 0x43, 0x2e, 0xc3, 0x37, 0x2b, 0xe0, 0xb4, 0x45, 0xa2, 0xaa, 0xc1, 0x34, 0x3c,
	0x4a, 0x7e, 0x0f, 0x1b, 0x89, 0xdd, 0xb3, 0x69, 0x94, 0xfe, 0xf7, 0xfe, 0x17, 0x7f, 0x04, 0xd9,
	0x68, 0x32, 0xb7, 0xfe, 0x1c, 0xf2, 0xde, 0xbc, 0xa3, 0x4e, 0x93, 0x51, 0xfc, 0x0c, 0x75, 0xfc,
	0x2b, 0xd4, 0xcd, 0x57, 0x06, 0x67, 0xaf, 0x84, 0x6e, 0x1f, 0xab, 0x62, 0x4f, 0xb0, 0x4e, 0xc7,
	0xed, 0xc4, 0xdf, 0x12, 0xc5, 0xd4, 0x60, 0x79, 0x39, 0x8f, 0xc7, 0x6e, 0xf8, 0x8a, 0x3d, 0x42,
	0x1e, 0x73, 0x5e, 0x2c, 0x38, 0x05, 0x5a, 0xee, 0x96, 0x8c, 0x02, 0xe6, 0xab, 0xb7, 0x75, 0x78,
	0xd3, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0xbb, 0xd3, 0xfd, 0xe1, 0x01, 0x00, 0x00,
}
